package betterklv

const (
	CHECKSUM_ID = 1 + iota
	UNIX_TIMESTAMP_ID
	MISSION_ID_ID
	PLATFORM_TAIL_NUMBER_ID
	PLATFORM_HEADING_ANGLE_ID
	PLATFORM_PITCH_ANGLE_ID
	PLATFORM_ROLL_ANGLE_ID
	PLATFORM_TRUE_AIRSPEED_ID
	PLATFORM_INDICATED_AIRSPEED_ID
	PLATFORM_DESIGNATION_ID
	IMAGE_SOURCE_SENSOR_ID
	IMAGE_COORDINATE_SYSTEM_ID
	SENSOR_LATITUDE_ID
	SENSOR_LONGITUDE_ID
	SENSOR_TRUE_ALTITUDE_ID
	SENSOR_HORIZONTAL_FOV_ID
	SENSOR_VERTICAL_FOV_ID
	SENSOR_RELATIVE_AZIMUTH_ID
	SENSOR_RELATIVE_ELEVATION_ID
	SENSOR_RELATIVE_ROLL_ID
	SLANT_RANGE_ID
	TARGET_WIDTH_ID
	FRAME_CENTER_LATITUDE_ID
	FRAME_CENTER_LONGITUDE_ID
	FRAME_CENTER_ELEVATION_ID
	OFFSET_CORNER_LATITUDE_1_ID
	OFFSET_CORNER_LONGITUDE_1_ID
	OFFSET_CORNER_LATITUDE_2_ID
	OFFSET_CORNER_LONGITUDE_2_ID
	OFFSET_CORNER_LATITUDE_3_ID
	OFFSET_CORNER_LONGITUDE_3_ID
	OFFSET_CORNER_LATITUDE_4_ID
	OFFSET_CORNER_LONGITUDE_4_ID
	ICING_DETECTED_ID
	WIND_DIRECTION_ID
	WIND_SPEED_ID
	STATIC_PRESSURE_ID
	DENSITY_ALTITUDE_ID
	OUTSIDE_AIR_TEMPERATURE_ID
	TARGET_LOCATION_LATITUDE_ID
	TARGET_LOCATION_LONGITUDE_ID
	TARGET_LOCATION_ELEVATION_ID
	TARGET_TRACK_GATE_WIDTH_ID
	TARGET_TRACK_GATE_HEIGHT_ID
	TARGET_ERROR_ESTIMATE_CE90_ID
	TARGET_ERROR_ESTIMATE_LE90_ID
	GENERIC_FLAG_DATA_ID
	SECURITY_LOCAL_METADATA_SET_ID
	DIFFERENTIAL_PRESSURE_ID
	PLATFORM_ANGLE_OF_ATTACK_ID
	PLATFORM_VERTICAL_SPEED_ID
	PLATFORM_SIDESLIP_ANGLE_ID
	AIRFIELD_BAROMETRIC_PRESSURE_ID
	AIRFIELD_ELEVATION_ID
	RELATIVE_HUMIDITY_ID
	PLATFORM_GROUND_SPEED_ID
	GROUD_RANGE_ID
	PLATFORM_FUEL_REMAINING_ID
	PLATFORM_CALL_SIGN_ID
	WEAPON_LOAD_ID
	WEAPON_FIRED_ID
	LASER_PRF_CODE_ID
	SENSOR_FOV_NAME_ID
	PLATFORM_MAGNETIC_HEADING_ID
	UAS_LS_VERSION_NUMBER_ID
	TARGET_LOCATION_COVARIANCE_MATRIX_ID
	ALTERNATE_PLATFORM_LATITUDE_ID
	ALTERNATE_PLATFORM_LONGITUDE_ID
	ALTERNATE_PLATFORM_ALTITUDE_ID
	ALTERNATE_PLATFORM_NAME_ID
	ALTERNATE_PLATFORM_HEADING_ID
	EVENT_START_TIME_UTC_ID
	RVT_LOCAL_SET_ID
	VMTI_DATA_SET_ID
	SENSOR_ELLIPSOID_HEIGHT_ID
	ALTERNATE_PLATFORM_ELLIPSOID_HEIGHT_ID
	OPERATIONAL_MODE_ID
	FRAME_CENTER_HEIGHT_ABOVE_ELLIPSOID_ID
	SENSOR_NORTH_VELOCITY_ID
	SENSOR_EAST_VELOCITY_ID
	IMAGE_HORIZON_PIXEL_PACK_ID
	CORNER_LATITUDE_POINT_1_FULL_ID
	CORNER_LONGITUDE_POINT_1_FULL_ID
	CORNER_LATITUDE_POINT_2_FULL_ID
	CORNER_LONGITUDE_POINT_2_FULL_ID
	CORNER_LATITUDE_POINT_3_FULL_ID
	CORNER_LONGITUDE_POINT_3_FULL_ID
	CORNER_LATITUDE_POINT_4_FULL_ID
	CORNER_LONGITUDE_POINT_4_FULL_ID
	PLATFORM_PITCH_ANGLE_FULL_ID
	PLATFORM_ROLL_ANGLE_FULL_ID
	PLATFORM_ANGLE_OF_ATTACK_FULL_ID
	PLATFORM_SIDESLIP_ANGLE_FULL_ID
	MIIS_CORE_IDENTIFIER_ID
	SAR_MOTION_IMAGERY_METADATA_ID
)

const (
	VMTI_SYSTEM_NAME_ID = 3 + iota
	VMTI_LDS_VERSION_NUMBER_ID
	TOTAL_NUMBER_OF_TARGETS_ID
	NUMBER_OF_REPORTED_TARGETS_ID
	VIDEO_FRAME_NUMBER_ID
	FRAME_WIDTH_ID
	FRAME_HEIGHT_ID
	VMTI_SOURCE_SENSOR_ID
	VMTI_SENSOR_HORIZONTAL_FOV_ID
	VMTI_SENSOR_VERTICAL_FOV_ID
	VTARGET_SERIES_ID = 101
)

const (
	TARGET_CENTROID_PIXEL_NUMBER_ID = 1 + iota
	BOUNDING_BOX_TOP_LEFT_PIXEL_NUMBER_ID
	BOUNDING_BOX_BOTTOM_RIGHT_PIXEL_NUMBER_ID
	TARGET_PRIORITY_ID
	TARGET_CONFIDENCE_LEVEL_ID
	TARGET_HISTORY_ID
	PERCENTAGE_OF_TARGET_PIXELS_ID
	TARGET_COLOR_ID
	TARGET_INTENSITY_ID
	TARGET_LOCATION_LATITUDE_OFFSET_ID
	TARGET_LOCATION_LONGITUDE_OFFSET_ID
	TARGET_HEIGHT_ID
	BOUNDING_BOX_TOP_LEFT_LATITUDE_OFFSET_ID
	BOUNDING_BOX_TOP_LEFT_LONGITUDE_OFFSET_ID
	BOUNDING_BOX_BOTTOM_RIGHT_LATITUDE_OFFSET_ID
	BOUNDING_BOX_BOTTOM_RIGHT_LONGITUDE_OFFSET_ID
	TARGET_LOCATION_ID
	TARGET_BOUNDARY_ID
	TARGET_CENTROID_PIXEL_ROW_ID
	TARGET_CENTROID_PIXEL_COLUMN_ID
	WAMI_FPA_INDEX_ID
	VMASK_LDS_ID
	VOBJECT_ID          = 102
	VFEATURE_LDS_ID     = 103
	VTRACKER_LDS_ID     = 104
	VCHIP_LDS_ID        = 105
	ONTOLOGY_ID         = 1
	CLASS_ID            = 2
	FEATURE_ID          = 2
	TARGET_ID_ID        = 1
	DETECTION_STATUS_ID = 2
	START_TIMESTAMP_ID  = 3
	END_TIMESTAMP_ID    = 4
	BOUNDING_BOX_ID     = 5
	ALGORITHM_ID        = 6
	CONFIDENCE_ID       = 7
	NUMBER_OF_POINTS_ID = 8
	LOCUS_ID            = 9
	VELOCITY_ID         = 10
	ACCELERATION_ID     = 11
)
